In [292]:
import pandas as pd

In [294]:
data = pd.read_csv(r'C:\Users\paton\Downloads\movie_rating.csv')
data.head()

   user_ID  rating                    title  timestamp
0        1       4         Toy Story (1995)  964982703
1        1       4  Grumpier Old Men (1995)  964981247
2        1       4              Heat (1995)  964982224
3        1       5     Bottle Rocket (1996)  964980868
4        1       4        Braveheart (1995)  964982176

In [296]:
movie_rating = data.pivot_table(index= ['user_ID'], columns=['title'], values='rating')
movie_rating.head()

title,8 Seconds (1994),"Air Up There, The (1994)",Airheads (1994),Aladdin (1992),Another Stakeout (1993),Apollo 13 (1995),"Aristocats, The (1970)",Assassins (1995),Babe (1995),"Babysitter, The (1995)",...,"Walking Dead, The (1995)","War, The (1994)",Waterworld (1995),White Squall (1996),Widows' Peak (1994),Wild Bill (1995),"Wild Bunch, The (1969)",With Honors (1994),Wolf (1994),Wyatt Earp (1994)
user_ID,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN
5,NaN,NaN,NaN,4.0,NaN,3.0,NaN,NaN,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [298]:
ToyStoryRating = movie_rating['Toy Story (1995)']
ToyStoryRating.head()

user_ID
1    4.0
2    NaN
3    NaN
4    NaN
5    4.0
Name: Toy Story (1995), dtype: float64

In [300]:
Similarmovies = movie_rating.corrwith(ToyStoryRating)
Similarmovies_cleaned = Similarmovies.dropna()

C:\Users\paton\anaconda3\Lib\site-packages\numpy\lib\function_base.py:2889: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
C:\Users\paton\anaconda3\Lib\site-packages\numpy\lib\function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
C:\Users\paton\anaconda3\Lib\site-packages\numpy\lib\function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
C:\Users\paton\anaconda3\Lib\site-packages\numpy\lib\function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\paton\anaconda3\Lib\site-packages\numpy\lib\function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

In [302]:
df_recommendation_movies = pd.DataFrame(Similarmovies_cleaned, columns= ['correlation'])
df_recommendation_movies

                       correlation
title
Aladdin (1992)            0.172516
Apollo 13 (1995)          0.850963
Babe (1995)               0.453743
Batman (1989)            -0.141421
Batman Forever (1995)     0.490990
...                            ...
Taxi Driver (1976)        0.500000
Tombstone (1993)          0.636364
Toy Story (1995)          1.000000
True Lies (1994)          0.447214
Waterworld (1995)         0.301511

[74 rows x 1 columns]

In [304]:
rating_count = data.groupby('title')['rating'].count()
rating_count

title
8 Seconds (1994)             1
Air Up There, The (1994)     2
Airheads (1994)              2
Aladdin (1992)              16
Another Stakeout (1993)      2
                            ..
Wild Bill (1995)             1
Wild Bunch, The (1969)       2
With Honors (1994)           3
Wolf (1994)                  2
Wyatt Earp (1994)            4
Name: rating, Length: 246, dtype: int64

In [306]:
df_recommendation_movies =df_recommendation_movies.join(rating_count.rename('num_rating'))
df_recommendation_movies.head()

                       correlation  num_rating
title
Aladdin (1992)            0.172516          16
Apollo 13 (1995)          0.850963          16
Babe (1995)               0.453743          11
Batman (1989)            -0.141421          19
Batman Forever (1995)     0.490990          13

In [308]:
recommendations = df_recommendation_movies[df_recommendation_movies['num_rating'] > 10]
recommendations

                         correlation  num_rating
title
Aladdin (1992)              0.172516          16
Apollo 13 (1995)            0.850963          16
Babe (1995)                 0.453743          11
Batman (1989)              -0.141421          19
Batman Forever (1995)       0.490990          13
Braveheart (1995)          -0.458333          16
Fargo (1996)               -0.102062          13
Forrest Gump (1994)         0.000000          26
Fugitive, The (1993)       -0.410792          18
Jurassic Park (1993)        0.436436          14
Lion King, The (1994)       0.639602          14
Mask, The (1994)            0.391304          12
Pretty Woman (1990)         0.870388          12
Pulp Fiction (1994)        -0.165295          26
Schindler's List (1993)     0.416667          16
Speed (1994)                0.301511          11
Stargate (1994)             0.000000          13
Toy Story (1995)            1.000000          15
True Lies (1994)            0.447214          14

In [310]:
recommendations = recommendations.sort_values('correlation', ascending=False).head(10)
recommendations

                         correlation  num_rating
title
Toy Story (1995)            1.000000          15
Pretty Woman (1990)         0.870388          12
Apollo 13 (1995)            0.850963          16
Lion King, The (1994)       0.639602          14
Batman Forever (1995)       0.490990          13
Babe (1995)                 0.453743          11
True Lies (1994)            0.447214          14
Jurassic Park (1993)        0.436436          14
Schindler's List (1993)     0.416667          16
Mask, The (1994)            0.391304          12

In [312]:
movierating_by_userID1 = data[data['user_ID'] == 1]['title']
movierating_by_userID1 = list(movierating_by_userID1)
movierating_by_userID1

['Toy Story (1995)',
 'Grumpier Old Men (1995)',
 'Heat (1995)',
 'Bottle Rocket (1996)',
 'Braveheart (1995)',
 'Rob Roy (1995)',
 'Canadian Bacon (1995)',
 'Desperado (1995)',
 'Billy Madison (1995)',
 'Clerks (1994)',
 'Ed Wood (1994)',
 'Pulp Fiction (1994)',
 'Stargate (1994)',
 'Tommy Boy (1995)',
 'Forrest Gump (1994)',
 'Jungle Book, The (1994)',
 'Mask, The (1994)',
 'Blown Away (1994)',
 'Fugitive, The (1993)',
 'Jurassic Park (1993)',
 'Mrs. Doubtfire (1993)',
 "Schindler's List (1993)",
 'Tombstone (1993)',
 'Batman (1989)',
 'Pinocchio (1940)',
 'Fargo (1996)']

In [314]:
recommendations = recommendations.index
correct = 0
for title in recommendations:
    if title in movierating_by_userID1:
        correct += 1
precision = correct / 10
print ("Precision@10 :" , precision)

Precision@10 : 0.4